services:
  frontend:
    image: demishuaccha/tingeso-m-frontend:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  frontend-gateway:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-gateway.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
