
services:
  frontend:
    container_name: tingeso-m-frontend
    image: demishuaccha/tingeso-m-frontend:latest
    ports:
      - "8070:8070"
    deploy:
      restart_policy:
        condition: on-failure